development:
  adapter: postgresql
  encoding: unicode
  database: rigelstpierre_development
  pool: 5
  username: rigelstpierre
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rigelstpierre_test
  pool: 5
  username: rigelstpierre
  password:
